# -*- coding: utf-8 -*-
"""ishamedit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U5cDZzqhIH4k4tEtyZPlfrOhQW7Pk0dP
"""

import os
os.chdir('/content/drive/My Drive/Hate Speech Detection/Project Codes/hate_ngram/')

# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""


import json as simplejson
from collections import Counter

file_list = os.listdir('/content/drive/My Drive/Hate Speech Detection/Project Codes/hate_ngram')
#print(file_list)
lineList = []
for filename in file_list:
    f = open(filename,'r')
    #lineList = [line.rstrip('\n') for line in open(filename)]
    for line in f:
      line_text = f.readline().rstrip()
      print(line_text)
      lineList.append(line_text)
    f.close()
#print(lineList)
print("finding duplicates...")
dup={}
c=0
for items in lineList:
  if items in dup.keys():
    dup[items]+=1
  else:
    dup[items]=1
for key in dup.keys():
  if dup[key]>1:
    c+=1
    print(key,dup[key])

f=open("/content/drive/My Drive/Hate Speech Detection/Project Codes/hate_bigrams_count.txt")
f.write(dup)

#f1 = open("/content/drive/My Drive/Hate Speech Detection/Project Codes/hate_words_for_count.txt",'w')
#simplejson.dump(lineList, f1)
#f1.close() 


'''
d = {};

# counting number of times each word comes up in list of words
for key in lineList: 
  #type(key)
  d[key] = d.get(key, 0) + 1

sorted(d.items(), key = lambda x: x[1], reverse = True)'''

import json

json = json.dumps(dup)
f = open("hate_word_count.json","w")
f.write(json)
f.close()

pwd